### ISSUE TITLE
Does not precompile on Mac OS 12.2, Intel Core i7, Julia 10.0.0

### ISSUE THREAD

**Issue by alexeyovchinnikov** [JuliaMath/IrrationalConstants.jl#30] opened 2024-01-31 18:43 UTC
Getting the following error. Any suggestions would be appreciated.
```
IrrationalConstants [92d709cd-6900-40b7-9082-c6be49f344b6]

Failed to precompile IrrationalConstants [92d709cd-6900-40b7-9082-c6be49f344b6] to "/Users/alexey/.julia/compiled/v1.10/IrrationalConstants/jl_jNJgAT".
[92697] signal (11.1): Segmentation fault: 11
in expression starting at /Users/alexey/.julia/packages/IrrationalConstants/vp5v4/src/stats.jl:3
unknown function (ip: 0x0)
Allocations: 2906 (Pool: 2897; Big: 9); GC: 
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types ~/.julia/juliaup/julia-1.10.0+0.x64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/Types.jl:70
  [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, timing::Bool, _from_loading::Bool, kwargs::@Kwargs{io::Base.TTY})
    @ Pkg.API ~/.julia/juliaup/julia-1.10.0+0.x64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/API.jl:1656
  [3] precompile(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::@Kwargs{_from_loading::Bool})
    @ Pkg.API ~/.julia/juliaup/julia-1.10.0+0.x64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/API.jl:159
  [4] precompile
    @ Pkg.API ~/.julia/juliaup/julia-1.10.0+0.x64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/API.jl:147 [inlined]
  [5] #precompile#114
    @ Pkg.API ~/.julia/juliaup/julia-1.10.0+0.x64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/API.jl:146 [inlined]
  [6] #invokelatest#2
    @ Base ./essentials.jl:889 [inlined]
  [7] invokelatest
    @ Base ./essentials.jl:884 [inlined]
  [8] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1957
  [9] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1806
 [10] #invoke_in_world#3
    @ Base ./essentials.jl:921 [inlined]
 [11] invoke_in_world
    @ Base ./essentials.jl:918 [inlined]
 [12] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1797
 [13] macro expansion
    @ Base ./loading.jl:1784 [inlined]
 [14] macro expansion
    @ Base ./lock.jl:267 [inlined]
 [15] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1747
 [16] #invoke_in_world#3
    @ Base ./essentials.jl:921 [inlined]
 [17] invoke_in_world
    @ Base ./essentials.jl:918 [inlined]
 [18] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1740
```

**Comment by devmotion** [comment] 2024-02-02 13:02
There's not much I can do here - I can't reproduce the issue (not the same specs but an M2 Mac). Did you try with a clean environment? And did you try to nuke (or probably safer, move) the `.julia` folder?

**Comment by alexeyovchinnikov** [comment] 2024-02-02 21:15
Thank you for looking into this! Yes, I tried installing on a fresh installation of Julia (without any additionally installed packages) - still the same issue.

**Comment by devmotion** [comment] 2024-02-02 21:53
> fresh installation of Julia

After deleting `/Users/alexey/.julia`?

**Comment by alexeyovchinnikov** [comment] 2024-02-02 22:32
Yes

**Comment by devmotion** [comment] 2024-10-09 08:47
I still haven't been able to reproduce this issue, neither locally nor on CI. Therefore I'll close this issue for now.

**Closed as completed by devmotion** 2024-10-09 08:47 UTC
